apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-to-github-deployment
  namespace: default
  labels:
    app: azure-devops-to-github-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-to-github-sample-app
  template:
    metadata:
      labels:
        app: azure-devops-to-github-sample-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: azure-devops-to-github
        image: ghcr.io/prashanth-volvocars/azure-devops-to-github:${COMMIT}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: ENV1
          value: ${ENV1}
        - name: ENV2
          value: ${ENV2}
        - name: OUTER_ENV
          value: ${OUTER_ENV}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 256m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 512Mi
      imagePullSecrets:
      - name: ghcr-cred