name: Azure DevOps To GitHub CI

on:
  pull_request:
    branches: [master]
  workflow_call:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push
      uses: prashanth-volvocars/build-and-push-action@master
      with:
        run_tests: "false"