name: Azure DevOps To GitHub CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-release:
    name: Pre-Release
    uses: ./.github/workflows/build-and-push.yaml

  deploy:
    name: Deploy
    needs: pre-release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        environment: [Dev]
        region: [ap-south-1]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Release
        uses: prashanth-volvocars/release-action@master
        with:
          aws_region: ${{ matrix.region }}
          aws_cluster_name: ${{ secrets.AWS_CLUSTER_NAME }}
          role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
          gh_pat: ${{ secrets.GH_PAT }}
          environment: ${{ matrix.environment }}
        env:
          COMMIT: ${{ github.sha }}